services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      - APP_NAME=myapp
      - DB_HOST=localhost
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
